---
title: "DSA5103 Final Project"
author: "Dylan Steimel and Constantine Kutson"
date: "10/27/2022"
output: pdf_document
---

```{r load_libs}
library(dplyr)
#install.packages("hash")
library(hash)
library(tidyverse)
library(lubridate)
```

```{r load_data}
data_2022 = read.csv(file = 'pbp-2022.csv')
data_2021 = read.csv(file = 'pbp-2021.csv')
data_2020 = read.csv(file = 'pbp-2020.csv')
data_2019 = read.csv(file = 'pbp-2019.csv')
data_2018 = read.csv(file = 'pbp-2018.csv')
data_2017 = read.csv(file = 'pbp-2017.csv')
data_2016 = read.csv(file = 'pbp-2016.csv')
data_2015 = read.csv(file = 'pbp-2015.csv')
data_2014 = read.csv(file = 'pbp-2014.csv')
data_2013 = read.csv(file = 'pbp-2013.csv')
```

```{r team_data}
team_names = unique(data_2021$OffenseTeam)
team_names = team_names[team_names != ""]

teams = hash()

for (t in team_names) {
  teams[[t]] = hash()
  #Get dataset for each team, also for this project we are only interested in Rush or Pass
  #We also drop features that are play results not game states
      ## i.e. We don't want our model realizing "RushDirection" == "" means pass!
  game_state_features = c("Quarter", "Minute", "Second", "OffenseTeam","DefenseTeam" ,"Down", "ToGo", "YardLine", "SeriesFirstDown", "SeasonYear", "Formation")
  targets = c("IsPass", "IsRush")
  misc = c("GameId","IsTouchdown") #Need to calculate score for features
  team_df = subset(data_2021, (OffenseTeam == t | DefenseTeam == t) & 
                     (IsRush == 1 | IsPass ==1),
                   select = c(game_state_features, targets, misc))
  #For Each team put games and plays in chronological order
  team_df = team_df[with(team_df, order(GameId, Quarter, desc(Minute), desc(Second), Down)), ]
  #Split team into games
  i = 1
  for (g in unique(team_df$GameId)){
    week = sprintf("Week %s", i)
    teams[[t]][[week]] = subset(team_df, GameId == g)
    i = i + 1
  }
}

#Example accessing data with hash NOTE: use double brackets
teams[["ARI"]][["Week 1"]]
```

```{r visualize_data}
pass_2021 = subset(data_2021, IsPass == 1)
rush_2021 = subset(data_2021, IsRush == 1)
pt = table(pass_2021$Quarter)
rt = table(rush_2021$Quarter)
#Get breakdown by quarter
Q1_table = c(pt["1"], rt["1"])
Q2_table = c(pt["2"], rt["2"])
Q3_table = c(pt["3"], rt["3"])
Q4_table = c(pt["4"], rt["4"])
#Get total plays
q1_plays = sum(Q1_table)
q2_plays = sum(Q2_table)
q3_plays = sum(Q3_table)
q4_plays = sum(Q4_table)
#Get percent pass/rush by quarter
Q1 = Q1_table / q1_plays
Q2 = Q2_table / q2_plays
Q3 = Q3_table / q3_plays
Q4 = Q4_table / q4_plays

bars = cbind(Q1, Q2, Q3, Q4)
barplot(bars, beside=TRUE, col=c("blue","green"))
legend("bottomright",c("Pass %","Rush %"),fill = c("blue","green"))
```

```{r}
#### Data Preparation ####

## Removing NA Rows From Quarter Column
data_2013 <- data_2013 %>% 
  drop_na(Quarter)

## Removing NA's from Date Column for Easier Data Conversion
data_2013 <- data_2013 %>% 
  drop_na(GameDate)

## Converting relevant columns to appropriate column types
data_2013 <- transform(data_2013, GameId = as.numeric(GameId),
                       Quarter = as.numeric(Quarter),
                       Minute = as.numeric(Minute), 
                       Second= as.numeric(Second),
                       Down = as.numeric(Down), 
                       ToGo = as.numeric(ToGo),
                       YardLine = as.numeric(YardLine), 
                       SeriesFirstDown = as.numeric(SeriesFirstDown),
                       NextScore = as.numeric(NextScore), 
                       TeamWin = as.numeric(TeamWin),
                       SeasonYear = as.numeric(SeasonYear),
                       Yards = as.numeric(Yards), 
                       IsRush = as.numeric(IsRush), 
                       IsPass = as.numeric(IsPass), 
                       IsIncomplete = as.numeric(IsIncomplete), 
                       IsSack = as.numeric(IsSack), 
                       IsChallenge = as.numeric(IsChallenge), 
                       IsTouchdown = as.numeric(IsTouchdown),
                       IsChallengeReversed = as.numeric(IsChallengeReversed),
                       IsMeasurement = as.numeric(IsMeasurement), 
                       IsInterception = as.numeric(IsInterception),
                       IsFumble = as.numeric(IsFumble), 
                       IsPenalty = as.numeric(IsPenalty), 
                       IsTwoPointConversion = as.numeric(IsTwoPointConversion),
                       IsTwoPointConversionSuccessful = as.numeric(IsTwoPointConversionSuccesful),
                       YardLineFixed = as.numeric(YardLineFixed), 
                       IsPenaltyAccepted = as.numeric(IsPenaltyAccepted), 
                       IsNoPlay = as.numeric(IsNoPlay), 
                       PenaltyYards = as.numeric(PenaltyYards))

## Turning Date Column Into column type (Date)
data_2013$GameDate <- ymd(data_2013$GameDate)
```

```{r}
#### Character Data Quality Report #### 

## Selecting variables based on column type
data_2013_character_variables <- data_2013 %>% 
  select_if(is.character)

data_2013_numeric_variables <- data_2013 %>% 
  select_if(is.numeric)

## Calculating empty observations
data_2013_chr_observations <- rbind(
        sum(data_2013$OffenseTeam != ""),
        sum(data_2013$DefenseTeam != ""),
        sum(data_2013$X != ""),
        sum(data_2013$X.1 != ""),
        sum(data_2013$Description != ""),
        sum(data_2013$X.2 != ""),
        sum(data_2013$X.3 != ""),
        sum(data_2013$Formation != ""),
        sum(data_2013$PlayType != ""),
        sum(data_2013$PassType != ""),
        sum(data_2013$Challenger != ""),
        sum(data_2013$RushDirection != ""),
        sum(data_2013$YardLineDirection != ""),
        sum(data_2013$PenaltyTeam != ""),
        sum(data_2013$PenaltyType != ""))

## Creating vector with column names
data_2013_variables <- c(colnames(data_2013_character_variables))

## Binding no observations with column name and cleaning table
N_Chr <- cbind(data_2013_variables, data_2013_chr_observations)
N_Chr <- as.data.frame(N_Chr)
N_Chr <- transform(N_Chr, Chr_Observations = as.numeric(V2))
N_Chr <- N_Chr[,-2]

## Calcuating unique variables across all columns
Unique_Chr_Variables <- rapply(data_2013_character_variables,function(x)length(unique(x)))

## Renaming and calculating missing percentages for final table
Character_Data_Report <- N_Chr %>% 
  rename(N = Chr_Observations) %>% 
  cbind(Unique_Chr_Variables) %>% 
  mutate(Missing = (17448 - N),
         Missing_Pct = (100 * (Missing / 17448)),
         Missing_Pct = round(Missing_Pct, digits = 1),
         Unique_Pct = ((Unique_Chr_Variables / N) * 100),
         Unique_Pct = round(Unique_Pct, digits = 1)) 

## Checking to see what is in these random columns
X <- data_2013$X
X1 <- data_2013$X.1
X2 <- data_2013$X.2
X3 <- data_2013$X.3
X_Columns <- as.data.frame(cbind(X, X1, X2, X3))
X_Columns <- X_Columns[!apply(X_Columns == "", 1, all),]
```

```{r}
#### Numeric Data Quality Report
Numeric_NA <- colSums(is.na(data_2013_numeric_variables))
Numeric_Colnames <- colnames(data_2013_numeric_variables)
Numeric_Rows <- rep(17448, 29)
N_Nur <- cbind(Numeric_Colnames, Numeric_Rows, Numeric_NA)
N_Nur <- as.data.frame(N_Nur)
N_Nur <- transform(N_Nur, Numeric_NA = as.numeric(Numeric_NA),
                   Numeric_Rows = as.numeric(Numeric_Rows))

Unique_Nur_Variables <- rapply(data_2013_numeric_variables,function(x)length(unique(x)))

Numeric_Data_Report <- N_Nur %>% 
  cbind(Unique_Nur_Variables) %>% 
  mutate(Missing_Pct = ((Numeric_NA/Numeric_Rows) * 100),
         Unique_Pct = ((Unique_Nur_Variables / Numeric_Rows) * 100),
         Missing_Pct = round(Missing_Pct, digits = 1),
         Unique_Pct = round(Unique_Pct, digits = 1)) %>% 
  dplyr::select(-Numeric_Colnames) %>% 
  rename(N = Numeric_Rows,
         Missing = Numeric_NA,
         "Unique Values" = Unique_Nur_Variables,
         "Missing Percentage" = Missing_Pct,
         "Unique Percentage" = Unique_Pct)
```

```{r}
Character_Data_Report %>% kable()
Numeric_Data_Report %>% kable()
```

